[package]
name = "cb"
version = "0.1.0"
authors = ["Bart≈Çomiej Kuras <hash.deb@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.7"
